# Generated by Django 5.2.8 on 2026-03-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_agent_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='session_id',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('regular', 'Regular'), ('uncensored', 'Uncensored'), ('ocr', 'OCR'), ('multi_debugger', 'Multi-Debugger')], default='regular', max_length=16),
        ),
    ]
